=== bhillebrecht/CertifiedML_PDE_AdvancedGeometries_AdvancedBoundaryTreatment/base_framework/json_schema_input/config_nn_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "/schemas/config_nn",
    "type": "object",
    "properties": {
      "input_dim": {
        "description": "Input dimension of the neural network (for time-dependent PINNs this is usually the state dimension plus 1).",
        "type": "integer"
      },
      "output_dim": {
        "description": "Output dimension of the neural network (for PINNs this is usually the state dimension).",
        "type": "integer"
      },
      "num_layers": {
        "description": "Number of hidden layers.",
        "type": "integer"
      },
      "num_neurons": {
        "description": "Number of neurons per hidden layer.",
        "type": "integer"
      },
      "lower_bound": {
        "description": "Lower bound for all input-dimensions. The array must have a length of input_dim.",
        "type": "array",
        "items": [
          {
            "type": "number"
          }
        ]
      },
      "upper_bound": {
        "description": "Upper bound for all input-dimensions. The array must have a length of input_dim",
        "type": "array",
        "items": [
          {
            "type": "number"
          }
        ]
      },
      "res_net_skip_length": {
        "description": "In case a residual neural network shall be built, the number of hidden layers to bypass shall be set here.",
        "type": "integer"
      }
    },
    "required": [
      "input_dim",
      "output_dim",
      "num_layers",
      "num_neurons",
      "lower_bound",
      "upper_bound"
    ]
  }

=== bhillebrecht/CertifiedML_PDE_AdvancedGeometries_AdvancedBoundaryTreatment/flow_around_cylinder/config_nn.json
{
    "input_dim" : 26,
    "output_dim" : 3,
    "num_layers" : 3,
    "num_neurons" : 40, 
    "lower_bound" : [0, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2],
    "upper_bound" : [4, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ]
}
